### ISSUE TITLE
4.1.2 Recorridos Adicionales

### ISSUE THREAD

**Issue by stri3d474** [stri3d474/Montes-de-Maria#11]
Yo como usuario necesito la creación de recorridos adicionales en el juego para aumentar el aprendizaje del usuario

- [x] Creación de los entornos adicionales 
- [x] Creación de las rutas para los entornos
- [x] Diseño de las interacciones en los entornos

**Comment by CryssthianRoa** [comment]
Se creo un mundo abierto el cual se puede recorrer libremente
